name: Setup CI
description: Setup CI

inputs:
  skip-cache:
    description: "Whether to skip the cache"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Set up pnpm
      uses: step-security/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version-file: ".node-version"
        cache: ${{ inputs.skip-cache != 'true' && 'pnpm' || '' }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
