name: Setup CI

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".node-version"
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
